.TH "Processus" 3 "Version 3" "Projet_ordonnancement_OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Processus
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <ProcStruct\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBpid\fP"
.br
.ti -1c
.RI "int \fBarrive\fP"
.br
.ti -1c
.RI "\fBCycle\fP \fBES\fP"
.br
.ti -1c
.RI "\fBCycle\fP \fBCPU\fP"
.br
.ti -1c
.RI "int \fBetat\fP"
.br
.ti -1c
.RI "int \fBtemps_fin\fP"
.br
.ti -1c
.RI "int \fBtemps_CPU\fP"
.br
.ti -1c
.RI "int \fBtemps_ES\fP"
.br
.ti -1c
.RI "int \fBtemps_premier_CPU\fP"
.br
.ti -1c
.RI "int \fBtemps_premier_CPU_verif\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int Processus::arrive"

.SS "\fBCycle\fP Processus::CPU"

.SS "\fBCycle\fP Processus::ES"

.SS "int Processus::etat"

.SS "int Processus::pid"

.SS "int Processus::temps_CPU"

.SS "int Processus::temps_ES"

.SS "int Processus::temps_fin"

.SS "int Processus::temps_premier_CPU"

.SS "int Processus::temps_premier_CPU_verif"


.SH "Author"
.PP 
Generated automatically by Doxygen for Projet_ordonnancement_OS from the source code\&.
