.TH "C:/Devoir/OS/Projet/Doxygen.debug/Inc/SJF.h" 3 "Version 3" "Projet_ordonnancement_OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Devoir/OS/Projet/Doxygen.debug/Inc/SJF.h
.SH SYNOPSIS
.br
.PP
\fR#include 'Liste\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBListe\fP \fBchercher_sjf\fP (\fBListe\fP l)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBListe\fP chercher_sjf (\fBListe\fP l)"
Parcourt une liste de processus et renvoie le processus prêt avec le plus petit temps d'éxecution 
.PP
\fBParameters\fP
.RS 4
\fIl\fP : La liste de processus 
.RE
.PP
\fBReturns\fP
.RS 4
Le processus prêt avec le temps d'éxecution le plus court, NULL sinon
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Projet_ordonnancement_OS from the source code\&.
