.TH "C:/Devoir/OS/Projet/Doxygen.debug/Src/SJRF.c" 3 "Version 3" "Projet_ordonnancement_OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Devoir/OS/Projet/Doxygen.debug/Src/SJRF.c
.SH SYNOPSIS
.br
.PP
\fR#include 'SJRF\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBListe\fP \fBchercher_sjrf\fP (\fBListe\fP l)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBListe\fP chercher_sjrf (\fBListe\fP l)"
Parcourt une liste de processus et renvoie le processus prêt ou en cours avec le plus petit temps d'éxecution, prendre en priorité les nouveaux arrivés si le temps d'éxecution est plus petit 
.PP
\fBParameters\fP
.RS 4
\fIl\fP : La liste de processus 
.RE
.PP
\fBReturns\fP
.RS 4
Le processus avec le temps d'éxecution le plus court, NULL sinon
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Projet_ordonnancement_OS from the source code\&.
