.TH "C:/Devoir/OS/Projet/Sources/Src Directory Reference" 3 "OS_projet_ordonnancement" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Devoir/OS/Projet/Sources/Src Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBCalcul_temps\&.c\fP"
.br
.ti -1c
.RI "file \fBlecture_fichier\&.c\fP"
.br
.ti -1c
.RI "file \fBListe\&.c\fP"
.br
.ti -1c
.RI "file \fBmain\&.c\fP"
.br
.ti -1c
.RI "file \fBordonnancement\&.c\fP"
.br
.ti -1c
.RI "file \fBProcStruct\&.c\fP"
.br
.ti -1c
.RI "file \fBSJF\&.c\fP"
.br
.ti -1c
.RI "file \fBSJRF\&.c\fP"
.br
.in -1c
