.TH "cellule" 3 "OS_projet_ordonnancement" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cellule
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <ProcStruct\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBduree\fP"
.br
.ti -1c
.RI "struct \fBcellule\fP * \fBsuivant\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int cellule::duree"

.SS "struct \fBcellule\fP* cellule::suivant"


.SH "Author"
.PP 
Generated automatically by Doxygen for OS_projet_ordonnancement from the source code\&.
