.TH "C:/Devoir/OS/Projet/Sources/Src/lecture_fichier.c" 3 "OS_projet_ordonnancement" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Devoir/OS/Projet/Sources/Src/lecture_fichier.c
.SH SYNOPSIS
.br
.PP
\fR#include 'lecture_fichier\&.h'\fP
.br
\fR#include <string\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBListe\fP \fBlire_processus\fP (const char *chemin)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBListe\fP lire_processus (const char * chemin)"
Lit un fichier de processus et retourne une liste de processus Format : pid arrive CPU\&.\&.\&. / ES\&.\&.\&. 
.PP
\fBParameters\fP
.RS 4
\fIchemin\fP : chemin vers le fichier 
.RE
.PP
\fBReturns\fP
.RS 4
la liste des processus lus
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for OS_projet_ordonnancement from the source code\&.
