.TH "C:/Devoir/OS/Projet/Sources/Src/main.c" 3 "OS_projet_ordonnancement" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Devoir/OS/Projet/Sources/Src/main.c
.SH SYNOPSIS
.br
.PP
\fR#include 'ordonnancement\&.h'\fP
.br
\fR#include 'lecture_fichier\&.h'\fP
.br
\fR#include <string\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBafficher_aide\fP ()"
.br
.ti -1c
.RI "\fBListe\fP \fBcreer_liste_defaut\fP ()"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void afficher_aide ()"
Afficher le texte d'aide pour l'utilisation en invité de commande après l'option -h
.SS "\fBListe\fP creer_liste_defaut ()"
Crée une liste de processus par défaut pour les tests 
.PP
\fBReturns\fP
.RS 4
la liste des processus
.RE
.PP

.SS "int main (int argc, char * argv[])"

.SH "Author"
.PP 
Generated automatically by Doxygen for OS_projet_ordonnancement from the source code\&.
